name: Tests
on:
  push:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            requirements/test_requirements.txt
      - name: Install python dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt
      - name: Run tests
        run: pytest tests